name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          python -m pip install poetry
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: View Poetry Help
        run: poetry --help

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Installing and updating factory_boy
        run: docker-compose exec -T web poetry add factory_boy@lates

      - name: Run migrations
        run: docker-compose exec -T web python manage.py migrate

      - name: Test
        run: docker-compose exec -T web python manage.py test

      - name: Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
