name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          python -m pip install poetry
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Installing dependencies
        run: |
          docker-compose exec -T web poetry install
          docker-compose exec -T web poetry add factory_boy@latest

      - name: Run migrations
        run: docker-compose exec -T web python manage.py migrate

      - name: Test
        run: docker-compose exec -T web poetry run pytest

      - name: Run Flake8 with ReviewDog
        uses: reviewdog/reviewdog@v1
        with:
          name: flake8
          reporter: github-pr-review
          level: warning
          filter_mode: added
          flake8_flags: "--config=.flake8"
          run: |
            docker-compose exec -T web flake8 --config=.flake8 .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
